<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.4</version>
        <relativePath/>
    </parent>

    <groupId>org.localhost</groupId>
    <artifactId>wms-employee-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>wms-employee-parent</name>
    <description>Parent project for WMS Employee</description>
    <packaging>pom</packaging>

    <properties>
        <java.version>17</java.version>
        <auth0.version>2.25.0</auth0.version>
        <mvc-auth-commons.version>1.2.0</mvc-auth-commons.version>
        <dotenv-java.version>3.0.0</dotenv-java.version>
    </properties>

    <modules>
        <module>wms-app</module>
        <module>auth-module</module>
        <module>domain-module</module>
        <module>employee-module</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.auth0</groupId>
                <artifactId>auth0</artifactId>
                <version>${auth0.version}</version>
            </dependency>
            <dependency>
                <groupId>com.auth0</groupId>
                <artifactId>mvc-auth-commons</artifactId>
                <version>${mvc-auth-commons.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cdimascio</groupId>
                <artifactId>dotenv-java</artifactId>
                <version>${dotenv-java.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>