-- Changeset 001: app-init
-- Create employee table based on the provided entity
CREATE TABLE IF NOT EXISTS employees
(
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supervisor_id     BIGINT       NOT NULL,
    username          VARCHAR(100) NOT NULL,
    name              VARCHAR(100) NOT NULL,
    surname           VARCHAR(100) NOT NULL,
    employee_role     VARCHAR(50)  NOT NULL,
    employee_status   VARCHAR(50)  NOT NULL,
    registration_date TIMESTAMP WITH TIME ZONE,
    auth0_user_id     VARCHAR(100) NOT NULL UNIQUE

);

-- Create employee_contact_details table
CREATE TABLE IF NOT EXISTS employee_contact_details
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id  BIGINT       NOT NULL UNIQUE,
    email        VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20)  NOT NULL,
    address      VARCHAR(255),
    city         VARCHAR(100),
    postal_code  VARCHAR(20),
    country      VARCHAR(100),
    edit_date    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_contact_details_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);



-- Create indexes
-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_employee_supervisor ON employees (supervisor_id);
CREATE INDEX IF NOT EXISTS idx_employee_status ON employees (employee_status);
CREATE INDEX IF NOT EXISTS idx_employee_role ON employees (employee_role);
CREATE INDEX IF NOT EXISTS idx_employee_contact_email ON employee_contact_details (email);

-- Reset sequences to ensure IDs start from 1
ALTER SEQUENCE employees_id_seq RESTART WITH 1;
ALTER SEQUENCE employee_contact_details_id_seq RESTART WITH 1;