@hostname = localhost
@port = 8080
@baseUrl = http://{{hostname}}:{{port}}/api/employee
@supervisorBaseUrl = http://{{hostname}}:{{port}}/api/supervisor
@supervisorId = 2
@employeeId = 1

### Rejestracja nowego pracownika
POST {{baseUrl}}
Content-Type: application/json

{
  "supervisorId": {{supervisorId}},
  "name": "test",
  "surname": "testowy",
  "email": "16082025@example.com",
  "phoneNumber": "+48123456789",
  "password": "Password@666",
  "confirmPassword": "Password@123",
  "employeeRole": "EMPLOYEE",
  "employeeStatus": "1",
  "address": "ul. Przykładowa 123",
  "city": "Warszawa",
  "postalCode": "00-001",
  "country": "Polska"
}


### Aktualizacja danych pracownika
PUT {{baseUrl}}
Content-Type: application/json

{
  "employeeId": 1,
  "name": "Jan",
  "surname": "Kowalski",
  "email": "jan.kowalski@example.com",
  "phoneNumber": "+48123456789",
  "status": "ACTIVE",
  "address": "ul. Słoneczna 45",
  "city": "Warszawa",
  "postalCode": "00-001",
  "country": "Polska"
}

### employye data update by supervisor
PUT {{baseUrl}}
Content-Type: application/json

{
  "employeeId": 1,
  "name": "Zupdatowy",
  "surname": "CRUD",
  "email": "jan.kowalski@example.com",
  "phoneNumber": "+48123456789",
  "status": "ACTIVE",
  "address": "ul. Słoneczna 45",
  "city": "Warszawa",
  "postalCode": "00-001",
  "country": "Polska"
}


### update employee status
PATCH {{supervisorBaseUrl}}/status
Content-Type: application/json

{
  "employeeId": 1,
  "managerId": 1,
  "status": "HOLIDAY"
}

### update employee role
PATCH {{supervisorBaseUrl}}/role
Content-Type: application/json

{
  "employeeId": 1,
  "managerId": 1,
  "role": "MANAGER"
}


### update employee status by employee
PATCH {{baseUrl}}/updateStatus
Content-Type: application/json

{
  "employeeId": 1,
  "managerId": 1,
  "status": "SUSPENDED"
}


